FROM node:lts

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies including development dependencies
RUN npm ci --also=dev

# Copy the source code to the working directory
COPY . .

# Expose the server port
EXPOSE 3000

# Start the development server with hot reloading
ENTRYPOINT [ "tail", "-f", "/dev/null" ]
# CMD [ "npm", "run", "dev" ]