version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linker_app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    container_name: linker_db
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: linker_redis
    env_file: .env
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
